# Database configuration
# type: sqlite | mysql
type: sqlite

sqlite:
  file: wildkits.db

mysql:
  host: localhost
  port: 3306
  database: wildkits
  username: root
  password: ''
  use-ssl: false

pool:
  maximum-pool-size: 10
  minimum-idle: 2
  connection-timeout: 30000
  max-lifetime: 1800000
